# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74128dce344a2e069b9d4469544096a3504135373494bb7ed45e2716440ed1c1e6fb844ec6b76a0ccb53a90884b74502cebdac31cd13c19923d5e91eadbd19a0

test:
  secret_key_base: 30ee8d9bd9a67d1a37cbc9d1ad2ca2ece52eb55aa47e4ed1dd7eb41936e20df26228bb5111aa25243eaaf3d129ba517438b74c0e7bf78e22edb8fcb27345377c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
